### ISSUE TITLE
Remove original API key 

### ISSUE THREAD

**Issue by JoykishanSharma** [madhuri-bh/NewsApp#1]
Hi @madhuri-bh  :wave:,
I wouldn't recommend adding your original NewsApi Key [here](https://github.com/madhuri-bh/NewsApp/blob/master/app/src/main/java/com/example/newsapp/utils/Constants.java#L11). Someone on the internet might use your api key. Instead you might wanna write something like this :point_down: 
```java
public static final String API_KEY = "your_news_api_key_here";
```
Although, It's pretty nice repo :smile: :+1: 
keep it up :1st_place_medal:

**Comment by madhuri-bh** [comment]
Thanks for your suggestion😊
I will surely correct it.
